spring:
  # DB 설정
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # mail yml 파일 저장 경로, 배포 시 경로 수정 필요
  config:
    import: file:C:\application-mail.yml
#    import: /home/ubuntu/spring/application-mail.yml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always

  # 멀티파트 최대 사이즈 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # 페이징 기본값 설정
  data:
    web:
      pageable:
        default-page-size: 15
        # 이거 쓰면 첫 페이지 인수 1부터 시작
#        one-indexed-parameters: true
  
  profiles:
    active: db

# 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie

# 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: info
