spring:
  # DB 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true

  # mail yml 파일 저장 경로, 배포 시 경로 수정 필요
  config:
#    import: file:C:\application-mail.yml
    import: file:///home/ubuntu/spring/application-mail.yml

  profiles:
    active: db, mail

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always

  # 멀티파트 최대 사이즈 설정
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  session:
    timeout: 900 # 15분


# 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true

# 로깅 레벨 설정
logging:
  config: classpath:logback-spring.xml
  level:
    root: info

