spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # mail yml 파일 저장 경로, 배포 시 경로 수정 필요
  config:
    import: file:C:\application-mail.yml
  profiles:
    active: db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    web:
      pageable:
        default-page-size: 15 # 페이징 기본 값

server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    org.hibernate.SQL: debug
